name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag node-easy:$(date +%s)

      - name: Publish Docker
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: ridvanuyn/easy-node
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          Dockerfile: Dockerfile
